project:
  type: website
  output-dir: .

website:
  title: "Juan Pablo Siachoque Campos"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: research.qmd
        text: Research

  page-footer: 
    right: "Copyright 2026, Juan Pablo Siachoque Campos" 
    left: 
      - icon: github
        href: https://github.com/juanpscampos
      - icon: twitter 
        href: https://x.com/juanpscampos
      - icon: linkedin 
        href: https://www.linkedin.com/in/juanpscampos/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

    website:
