project:
  type: website
  output-dir: .

website:
  title: "Juan Pablo Siachoque Campos"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: research.qmd
        text: Research
      - text: Resources
        menu:
          - text: Debt Sustainability
            href: resources.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

