project:
  type: website
  output-dir: outputs

website:
  title: "Juan Pablo Siachoque Campos"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: research.qmd
        text: Research